In [1]:
import numpy as np 

In [3]:
arr = np.array([1, 2, 3], dtype=np.float64)
print(arr)
print("Data type:", arr.dtype)

[1. 2. 3.]
Data type: float64


In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [7]:
arr = np.array([10, 20, 30, 40, 50])

# Access elements by index
print("First Element:", arr[0])
print("Last Element:", arr[-1])

# Slicing
print("First Three Elements:", arr[:3])
print("Elements from Index 2 to 4:", arr[2:5])

First Element: 10
Last Element: 50
First Three Elements: [10 20 30]
Elements from Index 2 to 4: [30 40 50]


In [9]:
arr = np.array([1, 2, 3])
print("Array + 10:", arr + 10)

Array + 10: [11 12 13]


In [11]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Element-wise multiplication
print("Element-wise Multiplication:\n", A * B)

# Matrix multiplication (dot product)
print("Matrix Multiplication:\n", np.dot(A, B))

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


In [13]:
from numpy.linalg import inv

A = np.array([[1, 2], [3, 4]])
print("Inverse:\n", inv(A))

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [15]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Element-wise Addition:\n", A + B)
print("Matrix Multiplication:\n", np.dot(A, B))

Element-wise Addition:
 [[ 6  8]
 [10 12]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


In [17]:
import numpy as np

arr = np.arange(10, 21, 2)
print("Original Array:", arr)

arr[arr > 15] = -1
print("Modified Array:", arr)

Original Array: [10 12 14 16 18 20]
Modified Array: [10 12 14 -1 -1 -1]


In [19]:
import numpy as np

identity_matrix = np.eye(3)
random_matrix = np.random.randint(1, 10, size=(3, 3))

print("Identity Matrix:\n", identity_matrix)
print("Random Matrix:\n", random_matrix)

result = np.dot(identity_matrix, random_matrix)
print("Result of Multiplication:\n", result)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Matrix:
 [[2 5 3]
 [2 6 5]
 [6 3 4]]
Result of Multiplication:
 [[2. 5. 3.]
 [2. 6. 5.]
 [6. 3. 4.]]


In [21]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

print("Original 2D Array:\n", a)
print("1D Array:", b)

result = a + b  # Broadcasting
print("Broadcasted Addition:\n", result)

Original 2D Array:
 [[1 2 3]
 [4 5 6]]
1D Array: [10 20 30]
Broadcasted Addition:
 [[11 22 33]
 [14 25 36]]


In [31]:
#explain np.ndim function with example

arr = np.array([[10,20,30,40],[2,3,4,5]])
print(arr.ndim) #ndim function returns the dimesnsion of the given array



2


In [53]:
#create an array of time for one hour with values of each second. This is the x value evaluate y= 2.pi .omega.x  and omega can be taken from user input

pi = np.pi

x = np.arange(0, 3600, 1)
def evaluate_y(omega):
    y = 2 * pi * omega * x
    return y
omega = float(input ("Enter value: ") )
y_values = evaluate_y(omega)
print(y_values[:10])

Enter value:  1.3


[ 0.          8.1681409  16.3362818  24.5044227  32.6725636  40.8407045
 49.0088454  57.1769863  65.34512719 73.51326809]
